MvcMusicStore/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMusicStore.Models;
using MvcMusicStore.ViewModels;

namespace MvcMusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        //Dependency Injection of Context
        MusicStoreEntities storeDB = new MusicStoreEntities();

        //
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            // Return te View
            return View(viewModel);
        }

        //
        // Get: /Store/AddtoCart/5

        public ActionResult AddToCart(int id)
        {

            // Retrieve the album from the database
            var addedAlbum = storeDB.Albums
                .Single(album => album.AlbumId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            //Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            //Get the name of the album to display confirmation
            string albumName = storeDB.Carts
                .Single(item => item.RecordId == id).Album.Title;

            // Remove from Cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        //
        // GET: /ShoppingCart/cartSummary

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");
        }
    }
}

MvcMusicStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMusicStore.Models;

namespace MvcMusicStore.Controllers
{
    public class StoreController : Controller
    {
        //Dependency Injection - Contructor Injection of a new StoreDB based on Music Store Etities shown below
        MusicStoreEntities storeDB = new MusicStoreEntities();

        // GET: Store
        public ActionResult Index()
        {
            var genres = storeDB.Genres.ToList();

            //What an idiot!! lol
            //foreach (var genre in storeDB.Genres)
            //{
            //    //var Genre = genre.Name.ToString();
            //}
            //Hardcoded List of Genres REMOVE
            //var genres = new List<Genre>
            //{
            //    new Genre {Name = "Disco"},
            //    new Genre {Name = "Jazz"},
            //    new Genre {Name = "Rock"},
            //};
            //return "Hello from Store.Index";
            return View(genres);
        }
        // GET: Store/Browse
        public ActionResult Browse(string genre)
        {
            //Retrieve Genre and its Associated Albums from database
            var genreModel = storeDB.Genres.Include("Albums")
                .Single(g => g.Name == genre);

            return View(genreModel);


            //OLD -return a ViewModel with a "Genre parameter" the "same value" as you pass into action
            //var genreModel = new Genre { Name = genre };
            //return View(genreModel);

            //string message = HttpUtility.HtmlEncode("Store.Browse, Genre = " + genre);
            //return message;
        }

        // GET: Store/Details
        public ActionResult Details(int id)
        {
            var album = storeDB.Albums.Find(id);

            return View(album);

            //Nick Attlee's way - My way
            //var album = storeDB.Albums.Where(a => a.AlbumId == id).FirstOrDefault();
            //return View(album);

            //OlD - Return an Album with a Hardcoded String plus the Id pAlbumsassed into the action
            //var album = new Album { Title = "Album " + id };
            //return View(album);
            
        }

        //
        //GET: /Store/GenreMenu
        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = storeDB.Genres.ToList();

            return PartialView(genres);
        }
    }
}

MvcMusicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="http://kendo.cdn.telerik.com/<kendo ui version>/js/kendo.all.min.js"></script>
    <script src="http://kendo.cdn.telerik.com/<kendo ui version>/js/kendo.aspnetmvc.min.js"></script>

</head>
<body>
        <div id="header">
            <h1>ASP.NET MVC MUSIC STORE</h1>
            <ul id="navlist">
                @*ADD NAV ICONS*@
                <li class="first "><a href="/" id="current"><img src="~/Content/glyphicons_free/glyphicons/png/glyphicons-21-home.png"/> Home</a></li>
                <li><a href="/Store/"><img src="~/Content/glyphicons_free/glyphicons/png/glyphicons-453-shop.png" /> Store</a></li>
                <li> @{Html.RenderAction("CartSummary", "ShoppingCart");} </li>
                <li><a href="/StoreManager/"><img src="~/Content/glyphicons_free/glyphicons/png/glyphicons-281-settings.png" /> Admin</a></li>
            </ul>
        </div>
        
    @*Render our Genre Side Menu List Partial View*@
        @{Html.RenderAction("GenreMenu", "Store"); }

        <div id="main">
            @RenderBody()
        </div>
        
        @*Changed from <footer> tag for css class*@
        <div id="footer">
            <p>&copy; @DateTime.Now.Year - Built using ASP.NET</p>
        </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>